<?php

class IconsHandler
{
    /**
     * Constructor
     */
    public function __construct() {

    }

      public static function getIcons(){
            return array(
                  'fa-adjust',
                  'fa-adn',
                  'fa-align-center',
                  'fa-align-justify',
                  'fa-align-left',
                  'fa-align-right',
                  'fa-ambulance',
                  'fa-anchor',
                  'fa-android',
                  'fa-angellist',
                  'fa-angle-double-down',
                  'fa-angle-double-left',
                  'fa-angle-double-right',
                  'fa-angle-double-up',
                  'fa-angle-down',
                  'fa-angle-left',
                  'fa-angle-right',
                  'fa-angle-up',
                  'fa-apple',
                  'fa-archive',
                  'fa-area-chart',
                  'fa-arrow-circle-down',
                  'fa-arrow-circle-left',
                  'fa-arrow-circle-o-down',
                  'fa-arrow-circle-o-left',
                  'fa-arrow-circle-o-right',
                  'fa-arrow-circle-o-up',
                  'fa-arrow-circle-right',
                  'fa-arrow-circle-up',
                  'fa-arrow-down',
                  'fa-arrow-left',
                  'fa-arrow-right',
                  'fa-arrow-up',
                  'fa-arrows',
                  'fa-arrows-alt',
                  'fa-arrows-h',
                  'fa-arrows-v',
                  'fa-asterisk',
                  'fa-at',
                  'fa-automobile',
                  'fa-backward',
                  'fa-ban',
                  'fa-bank',
                  'fa-bar-chart',
                  'fa-bar-chart-o',
                  'fa-barcode',
                  'fa-bars',
                  'fa-bed',
                  'fa-beer',
                  'fa-behance',
                  'fa-behance-square',
                  'fa-bell',
                  'fa-bell-o',
                  'fa-bell-slash',
                  'fa-bell-slash-o',
                  'fa-bicycle',
                  'fa-binoculars',
                  'fa-birthday-cake',
                  'fa-bitbucket',
                  'fa-bitbucket-square',
                  'fa-bitcoin',
                  'fa-bold',
                  'fa-bolt',
                  'fa-bomb',
                  'fa-book',
                  'fa-bookmark',
                  'fa-bookmark-o',
                  'fa-briefcase',
                  'fa-btc',
                  'fa-bug',
                  'fa-building',
                  'fa-building-o',
                  'fa-bullhorn',
                  'fa-bullseye',
                  'fa-bus',
                  'fa-buysellads',
                  'fa-cab',
                  'fa-calculator',
                  'fa-calendar',
                  'fa-calendar-o',
                  'fa-camera',
                  'fa-camera-retro',
                  'fa-car',
                  'fa-caret-down',
                  'fa-caret-left',
                  'fa-caret-right',
                  'fa-caret-square-o-down',
                  'fa-caret-square-o-left',
                  'fa-caret-square-o-right',
                  'fa-caret-square-o-up',
                  'fa-caret-up',
                  'fa-cart-arrow-down',
                  'fa-cart-plus',
                  'fa-cc',
                  'fa-cc-amex',
                  'fa-cc-discover',
                  'fa-cc-mastercard',
                  'fa-cc-paypal',
                  'fa-cc-stripe',
                  'fa-cc-visa',
                  'fa-certificate',
                  'fa-chain',
                  'fa-chain-broken',
                  'fa-check',
                  'fa-check-circle',
                  'fa-check-circle-o',
                  'fa-check-square',
                  'fa-check-square-o',
                  'fa-chevron-circle-down',
                  'fa-chevron-circle-left',
                  'fa-chevron-circle-right',
                  'fa-chevron-circle-up',
                  'fa-chevron-down',
                  'fa-chevron-left',
                  'fa-chevron-right',
                  'fa-chevron-up',
                  'fa-child',
                  'fa-circle',
                  'fa-circle-o',
                  'fa-circle-o-notch',
                  'fa-circle-thin',
                  'fa-clipboard',
                  'fa-clock-o',
                  'fa-close',
                  'fa-cloud',
                  'fa-cloud-download',
                  'fa-cloud-upload',
                  'fa-cny',
                  'fa-code',
                  'fa-code-fork',
                  'fa-codepen',
                  'fa-coffee',
                  'fa-cog',
                  'fa-cogs',
                  'fa-columns',
                  'fa-comment',
                  'fa-comment-o',
                  'fa-comments',
                  'fa-comments-o',
                  'fa-compass',
                  'fa-compress',
                  'fa-connectdevelop',
                  'fa-copy',
                  'fa-copyright',
                  'fa-credit-card',
                  'fa-crop',
                  'fa-crosshairs',
                  'fa-css3',
                  'fa-cube',
                  'fa-cubes',
                  'fa-cut',
                  'fa-cutlery',
                  'fa-dashboard',
                  'fa-dashcube',
                  'fa-database',
                  'fa-dedent',
                  'fa-delicious',
                  'fa-desktop',
                  'fa-deviantart',
                  'fa-diamond',
                  'fa-digg',
                  'fa-dollar',
                  'fa-dot-circle-o',
                  'fa-download',
                  'fa-dribbble',
                  'fa-dropbox',
                  'fa-drupal',
                  'fa-edit',
                  'fa-eject',
                  'fa-ellipsis-h',
                  'fa-ellipsis-v',
                  'fa-empire',
                  'fa-envelope',
                  'fa-envelope-o',
                  'fa-envelope-square',
                  'fa-eraser',
                  'fa-eur',
                  'fa-euro',
                  'fa-exchange',
                  'fa-exclamation',
                  'fa-exclamation-circle',
                  'fa-exclamation-triangle',
                  'fa-expand',
                  'fa-external-link',
                  'fa-external-link-square',
                  'fa-eye',
                  'fa-eye-slash',
                  'fa-eyedropper',
                  'fa-facebook',
                  'fa-facebook-f',
                  'fa-facebook-official',
                  'fa-facebook-square',
                  'fa-fast-backward',
                  'fa-fast-forward',
                  'fa-fax',
                  'fa-female',
                  'fa-fighter-jet',
                  'fa-file',
                  'fa-file-archive-o',
                  'fa-file-audio-o',
                  'fa-file-code-o',
                  'fa-file-excel-o',
                  'fa-file-image-o',
                  'fa-file-movie-o',
                  'fa-file-o',
                  'fa-file-pdf-o',
                  'fa-file-photo-o',
                  'fa-file-picture-o',
                  'fa-file-powerpoint-o',
                  'fa-file-sound-o',
                  'fa-file-text',
                  'fa-file-text-o',
                  'fa-file-video-o',
                  'fa-file-word-o',
                  'fa-file-zip-o',
                  'fa-files-o',
                  'fa-film',
                  'fa-filter',
                  'fa-fire',
                  'fa-fire-extinguisher',
                  'fa-flag',
                  'fa-flag-checkered',
                  'fa-flag-o',
                  'fa-flash',
                  'fa-flask',
                  'fa-flickr',
                  'fa-floppy-o',
                  'fa-folder',
                  'fa-folder-o',
                  'fa-folder-open',
                  'fa-folder-open-o',
                  'fa-font',
                  'fa-forumbee',
                  'fa-forward',
                  'fa-foursquare',
                  'fa-frown-o',
                  'fa-futbol-o',
                  'fa-gamepad',
                  'fa-gavel',
                  'fa-gbp',
                  'fa-ge',
                  'fa-gear',
                  'fa-gears',
                  'fa-genderless',
                  'fa-gift',
                  'fa-git',
                  'fa-git-square',
                  'fa-github',
                  'fa-github-alt',
                  'fa-github-square',
                  'fa-gittip',
                  'fa-glass',
                  'fa-globe',
                  'fa-google',
                  'fa-google-plus',
                  'fa-google-plus-square',
                  'fa-google-wallet',
                  'fa-graduation-cap',
                  'fa-gratipay',
                  'fa-group',
                  'fa-h-square',
                  'fa-hacker-news',
                  'fa-hand-o-down',
                  'fa-hand-o-left',
                  'fa-hand-o-right',
                  'fa-hand-o-up',
                  'fa-hdd-o',
                  'fa-header',
                  'fa-headphones',
                  'fa-heart',
                  'fa-heart-o',
                  'fa-heartbeat',
                  'fa-history',
                  'fa-home',
                  'fa-hospital-o',
                  'fa-hotel',
                  'fa-html5',
                  'fa-ils',
                  'fa-image',
                  'fa-inbox',
                  'fa-indent',
                  'fa-info',
                  'fa-info-circle',
                  'fa-inr',
                  'fa-instagram',
                  'fa-institution',
                  'fa-ioxhost',
                  'fa-italic',
                  'fa-joomla',
                  'fa-jpy',
                  'fa-jsfiddle',
                  'fa-key',
                  'fa-keyboard-o',
                  'fa-krw',
                  'fa-language',
                  'fa-laptop',
                  'fa-lastfm',
                  'fa-lastfm-square',
                  'fa-leaf',
                  'fa-leanpub',
                  'fa-legal',
                  'fa-lemon-o',
                  'fa-level-down',
                  'fa-level-up',
                  'fa-life-bouy',
                  'fa-life-buoy',
                  'fa-life-ring',
                  'fa-life-saver',
                  'fa-lightbulb-o',
                  'fa-line-chart',
                  'fa-link',
                  'fa-linkedin',
                  'fa-linkedin-square',
                  'fa-linux',
                  'fa-list',
                  'fa-list-alt',
                  'fa-list-ol',
                  'fa-list-ul',
                  'fa-location-arrow',
                  'fa-lock',
                  'fa-long-arrow-down',
                  'fa-long-arrow-left',
                  'fa-long-arrow-right',
                  'fa-long-arrow-up',
                  'fa-magic',
                  'fa-magnet',
                  'fa-mail-forward',
                  'fa-mail-reply',
                  'fa-mail-reply-all',
                  'fa-male',
                  'fa-map-marker',
                  'fa-mars',
                  'fa-mars-double',
                  'fa-mars-stroke',
                  'fa-mars-stroke-h',
                  'fa-mars-stroke-v',
                  'fa-maxcdn',
                  'fa-meanpath',
                  'fa-medium',
                  'fa-medkit',
                  'fa-meh-o',
                  'fa-mercury',
                  'fa-microphone',
                  'fa-microphone-slash',
                  'fa-minus',
                  'fa-minus-circle',
                  'fa-minus-square',
                  'fa-minus-square-o',
                  'fa-mobile',
                  'fa-mobile-phone',
                  'fa-money',
                  'fa-moon-o',
                  'fa-mortar-board',
                  'fa-motorcycle',
                  'fa-music',
                  'fa-navicon',
                  'fa-neuter',
                  'fa-newspaper-o',
                  'fa-openid',
                  'fa-outdent',
                  'fa-pagelines',
                  'fa-paint-brush',
                  'fa-paper-plane',
                  'fa-paper-plane-o',
                  'fa-paperclip',
                  'fa-paragraph',
                  'fa-paste',
                  'fa-pause',
                  'fa-paw',
                  'fa-paypal',
                  'fa-pencil',
                  'fa-pencil-square',
                  'fa-pencil-square-o',
                  'fa-phone',
                  'fa-phone-square',
                  'fa-photo',
                  'fa-picture-o',
                  'fa-pie-chart',
                  'fa-pied-piper',
                  'fa-pied-piper-alt',
                  'fa-pinterest',
                  'fa-pinterest-p',
                  'fa-pinterest-square',
                  'fa-plane',
                  'fa-play',
                  'fa-play-circle',
                  'fa-play-circle-o',
                  'fa-plug',
                  'fa-plus',
                  'fa-plus-circle',
                  'fa-plus-square',
                  'fa-plus-square-o',
                  'fa-power-off',
                  'fa-print',
                  'fa-puzzle-piece',
                  'fa-qq',
                  'fa-qrcode',
                  'fa-question',
                  'fa-question-circle',
                  'fa-quote-left',
                  'fa-quote-right',
                  'fa-ra',
                  'fa-random',
                  'fa-rebel',
                  'fa-recycle',
                  'fa-reddit',
                  'fa-reddit-square',
                  'fa-refresh',
                  'fa-remove',
                  'fa-renren',
                  'fa-reorder',
                  'fa-repeat',
                  'fa-reply',
                  'fa-reply-all',
                  'fa-retweet',
                  'fa-rmb',
                  'fa-road',
                  'fa-rocket',
                  'fa-rotate-left',
                  'fa-rotate-right',
                  'fa-rouble',
                  'fa-rss',
                  'fa-rss-square',
                  'fa-rub',
                  'fa-ruble',
                  'fa-rupee',
                  'fa-save',
                  'fa-scissors',
                  'fa-search',
                  'fa-search-minus',
                  'fa-search-plus',
                  'fa-sellsy',
                  'fa-send',
                  'fa-send-o',
                  'fa-server',
                  'fa-share',
                  'fa-share-alt',
                  'fa-share-alt-square',
                  'fa-share-square',
                  'fa-share-square-o',
                  'fa-shekel',
                  'fa-sheqel',
                  'fa-shield',
                  'fa-ship',
                  'fa-shirtsinbulk',
                  'fa-shopping-cart',
                  'fa-sign-in',
                  'fa-sign-out',
                  'fa-signal',
                  'fa-simplybuilt',
                  'fa-sitemap',
                  'fa-skyatlas',
                  'fa-skype',
                  'fa-slack',
                  'fa-sliders',
                  'fa-slideshare',
                  'fa-smile-o',
                  'fa-soccer-ball-o',
                  'fa-sort',
                  'fa-sort-alpha-asc',
                  'fa-sort-alpha-desc',
                  'fa-sort-amount-asc',
                  'fa-sort-amount-desc',
                  'fa-sort-asc',
                  'fa-sort-desc',
                  'fa-sort-down',
                  'fa-sort-numeric-asc',
                  'fa-sort-numeric-desc',
                  'fa-sort-up',
                  'fa-soundcloud',
                  'fa-space-shuttle',
                  'fa-spinner',
                  'fa-spoon',
                  'fa-spotify',
                  'fa-square',
                  'fa-square-o',
                  'fa-stack-exchange',
                  'fa-stack-overflow',
                  'fa-star',
                  'fa-star-half',
                  'fa-star-half-empty',
                  'fa-star-half-full',
                  'fa-star-half-o',
                  'fa-star-o',
                  'fa-steam',
                  'fa-steam-square',
                  'fa-step-backward',
                  'fa-step-forward',
                  'fa-stethoscope',
                  'fa-stop',
                  'fa-street-view',
                  'fa-strikethrough',
                  'fa-stumbleupon',
                  'fa-stumbleupon-circle',
                  'fa-subscript',
                  'fa-subway',
                  'fa-suitcase',
                  'fa-sun-o',
                  'fa-superscript',
                  'fa-support',
                  'fa-table',
                  'fa-tablet',
                  'fa-tachometer',
                  'fa-tag',
                  'fa-tags',
                  'fa-tasks',
                  'fa-taxi',
                  'fa-tencent-weibo',
                  'fa-terminal',
                  'fa-text-height',
                  'fa-text-width',
                  'fa-th',
                  'fa-th-large',
                  'fa-th-list',
                  'fa-thumb-tack',
                  'fa-thumbs-down',
                  'fa-thumbs-o-down',
                  'fa-thumbs-o-up',
                  'fa-thumbs-up',
                  'fa-ticket',
                  'fa-times',
                  'fa-times-circle',
                  'fa-times-circle-o',
                  'fa-tint',
                  'fa-toggle-down',
                  'fa-toggle-left',
                  'fa-toggle-off',
                  'fa-toggle-on',
                  'fa-toggle-right',
                  'fa-toggle-up',
                  'fa-train',
                  'fa-transgender',
                  'fa-transgender-alt',
                  'fa-trash',
                  'fa-trash-o',
                  'fa-tree',
                  'fa-trello',
                  'fa-trophy',
                  'fa-truck',
                  'fa-try',
                  'fa-tty',
                  'fa-tumblr',
                  'fa-tumblr-square',
                  'fa-turkish-lira',
                  'fa-twitch',
                  'fa-twitter',
                  'fa-twitter-square',
                  'fa-umbrella',
                  'fa-underline',
                  'fa-undo',
                  'fa-university',
                  'fa-unlink',
                  'fa-unlock',
                  'fa-unlock-alt',
                  'fa-unsorted',
                  'fa-upload',
                  'fa-usd',
                  'fa-user',
                  'fa-user-md',
                  'fa-user-plus',
                  'fa-user-secret',
                  'fa-user-times',
                  'fa-users',
                  'fa-venus',
                  'fa-venus-double',
                  'fa-venus-mars',
                  'fa-viacoin',
                  'fa-video-camera',
                  'fa-vimeo-square',
                  'fa-vine',
                  'fa-vk',
                  'fa-volume-down',
                  'fa-volume-off',
                  'fa-volume-up',
                  'fa-warning',
                  'fa-wechat',
                  'fa-weibo',
                  'fa-weixin',
                  'fa-whatsapp',
                  'fa-wheelchair',
                  'fa-wifi',
                  'fa-windows',
                  'fa-won',
                  'fa-wordpress',
                  'fa-wrench',
                  'fa-xing',
                  'fa-xing-square',
                  'fa-yahoo',
                  'fa-yelp',
                  'fa-yen',
                  'fa-youtube',
                  'fa-youtube-play',
                  'fa-youtube-square',
            );
      }

      public static function getDashIcons() {

            return array(
                  'admin-appearance' => __('appearance', 'smooth-scroll-up'),
                  'admin-collapse' => __('collapse', 'smooth-scroll-up'),
                  'admin-comments' => __('comments', 'smooth-scroll-up'),
                  'admin-generic' => __('generic', 'smooth-scroll-up'),
                  'admin-home' => __('home', 'smooth-scroll-up'),
                  'admin-links' => __('links', 'smooth-scroll-up'),
                  'admin-media' => __('media', 'smooth-scroll-up'),
                  'admin-network' => __('network', 'smooth-scroll-up'),
                  'admin-page' => __('page', 'smooth-scroll-up'),
                  'admin-plugins' => __('plugins', 'smooth-scroll-up'),
                  'admin-post' => __('post', 'smooth-scroll-up'),
                  'admin-settings' => __('settings', 'smooth-scroll-up'),
                  'admin-site' => __('site', 'smooth-scroll-up'),
                  'admin-tools' => __('tools', 'smooth-scroll-up'),
                  'admin-users' => __('users', 'smooth-scroll-up'),
                  'album' => __('album', 'smooth-scroll-up'),
                  'align-center' => __('align center', 'smooth-scroll-up'),
                  'align-left' => __('align left', 'smooth-scroll-up'),
                  'align-none' => __('align none', 'smooth-scroll-up'),
                  'align-right' => __('align right', 'smooth-scroll-up'),
                  'analytics' => __('analytics', 'smooth-scroll-up'),
                  'archive' => __('archive', 'smooth-scroll-up'),
                  'arrow-down-alt2' => __('down alt2', 'smooth-scroll-up'),
                  'arrow-down-alt' => __('down alt', 'smooth-scroll-up'),
                  'arrow-down' => __('down', 'smooth-scroll-up'),
                  'arrow-left-alt2' => __('left alt2', 'smooth-scroll-up'),
                  'arrow-left-alt' => __('left alt', 'smooth-scroll-up'),
                  'arrow-left' => __('left', 'smooth-scroll-up'),
                  'arrow-right-alt2' => __('right alt2', 'smooth-scroll-up'),
                  'arrow-right-alt' => __('right alt', 'smooth-scroll-up'),
                  'arrow-right' => __('right', 'smooth-scroll-up'),
                  'arrow-up-alt2' => __('up alt2', 'smooth-scroll-up'),
                  'arrow-up-alt' => __('up alt', 'smooth-scroll-up'),
                  'arrow-up' => __('up', 'smooth-scroll-up'),
                  'art' => __('art', 'smooth-scroll-up'),
                  'awards' => __('awards', 'smooth-scroll-up'),
                  'backup' => __('backup', 'smooth-scroll-up'),
                  'book-alt' => __('book alt', 'smooth-scroll-up'),
                  'book' => __('book', 'smooth-scroll-up'),
                  'building' => __('building', 'smooth-scroll-up'),
                  'businessman' => __('businessman', 'smooth-scroll-up'),
                  'calendar-alt' => __('calendar alt', 'smooth-scroll-up'),
                  'calendar' => __('calendar', 'smooth-scroll-up'),
                  'camera' => __('camera', 'smooth-scroll-up'),
                  'carrot' => __('carrot', 'smooth-scroll-up'),
                  'cart' => __('cart', 'smooth-scroll-up'),
                  'category' => __('category', 'smooth-scroll-up'),
                  'chart-area' => __('chart area', 'smooth-scroll-up'),
                  'chart-bar' => __('chart bar', 'smooth-scroll-up'),
                  'chart-line' => __('chart line', 'smooth-scroll-up'),
                  'chart-pie' => __('chart pie', 'smooth-scroll-up'),
                  'clipboard' => __('clipboard', 'smooth-scroll-up'),
                  'clock' => __('clock', 'smooth-scroll-up'),
                  'cloud' => __('cloud', 'smooth-scroll-up'),
                  'controls-back' => __('back', 'smooth-scroll-up'),
                  'controls-forward' => __('forward', 'smooth-scroll-up'),
                  'controls-pause' => __('pause', 'smooth-scroll-up'),
                  'controls-play' => __('play', 'smooth-scroll-up'),
                  'controls-repeat' => __('repeat', 'smooth-scroll-up'),
                  'controls-skipback' => __('skip back', 'smooth-scroll-up'),
                  'controls-skipforward' => __('skip forward', 'smooth-scroll-up'),
                  'controls-volumeoff' => __('volume off', 'smooth-scroll-up'),
                  'controls-volumeon' => __('volume on', 'smooth-scroll-up'),
                  'dashboard' => __('dashboard', 'smooth-scroll-up'),
                  'desktop' => __('desktop', 'smooth-scroll-up'),
                  'dismiss' => __('dismiss', 'smooth-scroll-up'),
                  'download' => __('download', 'smooth-scroll-up'),
                  'editor-aligncenter' => __('align center', 'smooth-scroll-up'),
                  'editor-alignleft' => __('align left', 'smooth-scroll-up'),
                  'editor-alignright' => __('align right', 'smooth-scroll-up'),
                  'editor-bold' => __('bold', 'smooth-scroll-up'),
                  'editor-break' => __('break', 'smooth-scroll-up'),
                  'editor-code' => __('code', 'smooth-scroll-up'),
                  'editor-contract' => __('contract', 'smooth-scroll-up'),
                  'editor-customchar' => __('custom char', 'smooth-scroll-up'),
                  'editor-distractionfree' => __('distraction free', 'smooth-scroll-up'),
                  'editor-expand' => __('expand', 'smooth-scroll-up'),
                  'editor-help' => __('help', 'smooth-scroll-up'),
                  'editor-indent' => __('indent', 'smooth-scroll-up'),
                  'editor-insertmore' => __('insert more', 'smooth-scroll-up'),
                  'editor-italic' => __('italic', 'smooth-scroll-up'),
                  'editor-justify' => __('justify', 'smooth-scroll-up'),
                  'editor-kitchensink' => __('kitchen sink', 'smooth-scroll-up'),
                  'editor-ol' => __('ol', 'smooth-scroll-up'),
                  'editor-outdent' => __('outdent', 'smooth-scroll-up'),
                  'editor-paragraph' => __('paragraph', 'smooth-scroll-up'),
                  'editor-paste-text' => __('paste text', 'smooth-scroll-up'),
                  'editor-paste-word' => __('paste word', 'smooth-scroll-up'),
                  'editor-quote' => __('quote', 'smooth-scroll-up'),
                  'editor-removeformatting' => __('remove formatting', 'smooth-scroll-up'),
                  'editor-rtl' => __('rtl', 'smooth-scroll-up'),
                  'editor-spellcheck' => __('spellcheck', 'smooth-scroll-up'),
                  'editor-strikethrough' => __('strike through', 'smooth-scroll-up'),
                  'editor-textcolor' => __('text color', 'smooth-scroll-up'),
                  'editor-ul' => __('ul', 'smooth-scroll-up'),
                  'editor-underline' => __('underline', 'smooth-scroll-up'),
                  'editor-unlink' => __('unlink', 'smooth-scroll-up'),
                  'editor-video' => __('video', 'smooth-scroll-up'),
                  'edit' => __('edit', 'smooth-scroll-up'),
                  'email-alt' => __('email alt', 'smooth-scroll-up'),
                  'email' => __('email', 'smooth-scroll-up'),
                  'excerpt-view' => __('excerpt view', 'smooth-scroll-up'),
                  'exerpt-view' => __('exerpt view', 'smooth-scroll-up'),
                  'external' => __('external', 'smooth-scroll-up'),
                  'facebook-alt' => __('facebook alt', 'smooth-scroll-up'),
                  'facebook' => __('facebook', 'smooth-scroll-up'),
                  'feedback' => __('feedback', 'smooth-scroll-up'),
                  'flag' => __('flag', 'smooth-scroll-up'),
                  'format-aside' => __('aside', 'smooth-scroll-up'),
                  'format-audio' => __('audio', 'smooth-scroll-up'),
                  'format-chat' => __('chat', 'smooth-scroll-up'),
                  'format-gallery' => __('gallery', 'smooth-scroll-up'),
                  'format-image' => __('image', 'smooth-scroll-up'),
                  'format-links' => __('links', 'smooth-scroll-up'),
                  'format-quote' => __('quote', 'smooth-scroll-up'),
                  'format-standard' => __('standard', 'smooth-scroll-up'),
                  'format-status' => __('status', 'smooth-scroll-up'),
                  'format-video' => __('video', 'smooth-scroll-up'),
                  'forms' => __('forms', 'smooth-scroll-up'),
                  'googleplus' => __('google plus', 'smooth-scroll-up'),
                  'grid-view' => __('grid view', 'smooth-scroll-up'),
                  'groups' => __('groups', 'smooth-scroll-up'),
                  'hammer' => __('hammer', 'smooth-scroll-up'),
                  'heart' => __('heart', 'smooth-scroll-up'),
                  'id-alt' => __('id alt', 'smooth-scroll-up'),
                  'id' => __('id', 'smooth-scroll-up'),
                  'images-alt2' => __('images alt2', 'smooth-scroll-up'),
                  'images-alt' => __('images alt', 'smooth-scroll-up'),
                  'image-crop' => __('image crop', 'smooth-scroll-up'),
                  'image-flip-horizontal' => __('image flip horizontal', 'smooth-scroll-up'),
                  'image-flip-vertical' => __('image flip vertical', 'smooth-scroll-up'),
                  'image-rotate-left' => __('image rotate left', 'smooth-scroll-up'),
                  'image-rotate-right' => __('image rotate right', 'smooth-scroll-up'),
                  'index-card' => __('index card', 'smooth-scroll-up'),
                  'info' => __('info', 'smooth-scroll-up'),
                  'leftright' => __('left right', 'smooth-scroll-up'),
                  'lightbulb' => __('light bulb', 'smooth-scroll-up'),
                  'list-view' => __('list view', 'smooth-scroll-up'),
                  'location-alt' => __('location alt', 'smooth-scroll-up'),
                  'location' => __('location', 'smooth-scroll-up'),
                  'lock' => __('lock', 'smooth-scroll-up'),
                  'marker' => __('marker', 'smooth-scroll-up'),
                  'media-archive' => __('media archive', 'smooth-scroll-up'),
                  'media-audio' => __('media audio', 'smooth-scroll-up'),
                  'media-code' => __('media code', 'smooth-scroll-up'),
                  'media-default' => __('media default', 'smooth-scroll-up'),
                  'media-document' => __('media document', 'smooth-scroll-up'),
                  'media-interactive' => __('media interactive', 'smooth-scroll-up'),
                  'media-spreadsheet' => __('media spreadsheet', 'smooth-scroll-up'),
                  'media-text' => __('media text', 'smooth-scroll-up'),
                  'media-video' => __('media video', 'smooth-scroll-up'),
                  'megaphone' => __('megaphone', 'smooth-scroll-up'),
                  'menu' => __('menu', 'smooth-scroll-up'),
                  'microphone' => __('microphone', 'smooth-scroll-up'),
                  'migrate' => __('migrate', 'smooth-scroll-up'),
                  'minus' => __('minus', 'smooth-scroll-up'),
                  'money' => __('money', 'smooth-scroll-up'),
                  'nametag' => __('name tag', 'smooth-scroll-up'),
                  'networking' => __('networking', 'smooth-scroll-up'),
                  'no-alt' => __('no alt', 'smooth-scroll-up'),
                  'no' => __('no', 'smooth-scroll-up'),
                  'palmtree' => __('palm tree', 'smooth-scroll-up'),
                  'performance' => __('performance', 'smooth-scroll-up'),
                  'phone' => __('phone', 'smooth-scroll-up'),
                  'playlist-audio' => __('playlist audio', 'smooth-scroll-up'),
                  'playlist-video' => __('playlist video', 'smooth-scroll-up'),
                  'plus-alt' => __('plus alt', 'smooth-scroll-up'),
                  'plus' => __('plus', 'smooth-scroll-up'),
                  'portfolio' => __('portfolio', 'smooth-scroll-up'),
                  'post-status' => __('post status', 'smooth-scroll-up'),
                  'post-trash' => __('post trash', 'smooth-scroll-up'),
                  'pressthis' => __('press this', 'smooth-scroll-up'),
                  'products' => __('products', 'smooth-scroll-up'),
                  'randomize' => __('randomize', 'smooth-scroll-up'),
                  'redo' => __('redo', 'smooth-scroll-up'),
                  'rss' => __('rss', 'smooth-scroll-up'),
                  'schedule' => __('schedule', 'smooth-scroll-up'),
                  'screenoptions' => __('screen options', 'smooth-scroll-up'),
                  'search' => __('search', 'smooth-scroll-up'),
                  'share1' => __('share1', 'smooth-scroll-up'),
                  'share-alt2' => __('share alt2', 'smooth-scroll-up'),
                  'share-alt' => __('share alt', 'smooth-scroll-up'),
                  'share' => __('share', 'smooth-scroll-up'),
                  'shield-alt' => __('shield alt', 'smooth-scroll-up'),
                  'shield' => __('shield', 'smooth-scroll-up'),
                  'slides' => __('slides', 'smooth-scroll-up'),
                  'smartphone' => __('smartphone', 'smooth-scroll-up'),
                  'smiley' => __('smiley', 'smooth-scroll-up'),
                  'sort' => __('sort', 'smooth-scroll-up'),
                  'sos' => __('sos', 'smooth-scroll-up'),
                  'star-empty' => __('star empty', 'smooth-scroll-up'),
                  'star-filled' => __('star filled', 'smooth-scroll-up'),
                  'star-half' => __('star half', 'smooth-scroll-up'),
                  'store' => __('store', 'smooth-scroll-up'),
                  'tablet' => __('tablet', 'smooth-scroll-up'),
                  'tagcloud' => __('tag cloud', 'smooth-scroll-up'),
                  'tag' => __('tag', 'smooth-scroll-up'),
                  'testimonial' => __('testimonial', 'smooth-scroll-up'),
                  'text' => __('text', 'smooth-scroll-up'),
                  'tickets-alt' => __('tickets alt', 'smooth-scroll-up'),
                  'tickets' => __('tickets', 'smooth-scroll-up'),
                  'translation' => __('translation', 'smooth-scroll-up'),
                  'trash' => __('trash', 'smooth-scroll-up'),
                  'twitter' => __('twitter', 'smooth-scroll-up'),
                  'undo' => __('undo', 'smooth-scroll-up'),
                  'universal-access-alt' => __('universal access alt', 'smooth-scroll-up'),
                  'universal-access' => __('universal access', 'smooth-scroll-up'),
                  'update' => __('update', 'smooth-scroll-up'),
                  'upload' => __('upload', 'smooth-scroll-up'),
                  'vault' => __('vault', 'smooth-scroll-up'),
                  'video-alt2' => __('video alt2', 'smooth-scroll-up'),
                  'video-alt3' => __('video alt3', 'smooth-scroll-up'),
                  'video-alt' => __('video alt', 'smooth-scroll-up'),
                  'visibility' => __('visibility', 'smooth-scroll-up'),
                  'welcome-add-page' => __('add page', 'smooth-scroll-up'),
                  'welcome-comments' => __('comments', 'smooth-scroll-up'),
                  'welcome-edit-page' => __('edit page', 'smooth-scroll-up'),
                  'welcome-learn-more' => __('learn more', 'smooth-scroll-up'),
                  'welcome-view-site' => __('view site', 'smooth-scroll-up'),
                  'welcome-widgets-menus' => __('widgets menus', 'smooth-scroll-up'),
                  'welcome-write-blog' => __('write blog', 'smooth-scroll-up'),
                  'wordpress-alt' => __('wordpress alt', 'smooth-scroll-up'),
                  'wordpress' => __('wordpress', 'smooth-scroll-up'),
                  'yes' => __('yes', 'smooth-scroll-up'),
            );

      }

}
